name: "Update Rebrandly Link"
inputs:
  apikey:
    description: 'API Key to access Rebrandly'
    required: true
  domain:
    description: 'Domain name used for link'
    required: true
  slashtag:
    description: 'Slashtag value for link'
    required: true
  destination:
    description: 'New destination for link'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check Runner OS
      shell: bash
      env:
        RUNNER_OS: ${{ runner.os }}
      run: |
        if [ "$RUNNER_OS" != "Linux" ]; then
          echo "[!] This workflow only supports Linux runners"
          exit 1
        fi

    - name: Get Link ID
      id: get-link-id
      shell: bash
      env:
        APIKEY: ${{ inputs.apikey }}
        DOMAIN: ${{ inputs.domain }}
        SLASHTAG: ${{ inputs.slashtag }}
      run: |
        ID=$(curl --silent --request GET \
          --url "https://api.rebrandly.com/v1/links?domain.fullName=$DOMAIN&slashtag=$SLASHTAG" \
          --header "Accept: application/json" \
          --header "apikey: $APIKEY" | jq -r '.[0].id')
        echo "id=$ID" >> $GITHUB_OUTPUT

    - name: Update Link Destination
      shell: bash
      env:
        APIKEY: ${{ inputs.apikey }}
        ID: ${{ steps.get-link-id.outputs.id }}
        DESTINATION: ${{ inputs.destination }}
      run: |
        RESULT=$(curl --silent --request POST \
          --url https://api.rebrandly.com/v1/links/$ID \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --header "apikey: $APIKEY" \
          --data "{\"destination\": \"$DESTINATION\"}")
        echo $RESULT | jq '.shortUrl, .destination, .updatedAt'
