---

name: CI-Lint

on:
  push:
    paths:
      - "lint-workflow/**"

jobs:
  CI:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Set up Python
        uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pyyaml urllib3
      - name: Test lint
        run: pytest
        working-directory: lint-workflow/tests
