---

name: Test Version Bump Action

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "New Version"
        required: true

jobs:
  test-version-bumps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Bump JSON Test
        id: test_json
        uses: ./version-bump
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "./version-bump/tests/fixtures/package-lock.json"

      - name: Bump PLIST Test
        id: test_plist
        uses: ./version-bump
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "./version-bump/tests/fixtures/Info.plist"

      - name: Bump XML Test
        id: test_xml
        uses: ./version-bump
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "./version-bump/tests/fixtures/AndroidManifest.xml"

      - name: Bump Props Test
        id: test_props
        uses: ./version-bump
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "./version-bump/tests/fixtures/dir.build.props"

      - name: Bump CSProj Test
        id: test_csproj
        uses: ./version-bump
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "./version-bump/tests/fixtures/test.csproj"

      - name: Validate Outputs
        run: |
          echo "${{ steps.test_json.outputs.status }}"
          echo "${{ steps.test_plist.outputs.status }}"
          echo "${{ steps.test_xml.outputs.status }}"
          echo "${{ steps.test_props.outputs.status }}"
          echo "${{ steps.test_csproj.outputs.status }}"
