---

name: Test Version Bump Action

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "New Version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Bump JSON Test
        id: test_json
        uses: ./version-bump
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "./version-bump/tests/package-lock.json"

      - name: Bump PLIST Test
        id: test_plist
        uses: ./version-bump
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "./version-bump/tests/Info.plist"

      - name: Bump XML Test
        id: test_xml
        uses: ./version-bump
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "./version-bump/tests/AndroidManifest.xml"

      - name: Bump Props Test
        id: test_props
        uses: ./version-bump
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "./version-bump/tests/dir.build.props"

      - name: Validate Outputs
        run: |
          echo "${{ steps.test_json.outputs.status }}"
          echo "${{ steps.test_plist.outputs.status }}"
          echo "${{ steps.test_xml.outputs.status }}"
          echo "${{ steps.test_props.outputs.status }}"

      