---
name: Test report-deployment-status-to-slack
on:
  pull_request:
      paths:
      - "./report-deployment-status-to-slack"
      - ".github/workflows/test-report-deployment-status-to-slack.yml"

jobs:
  test-report:
    name: Test Slack report
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: ./report-deployment-status-to-slack
        with:
          environment: US QA Cloud
          tag: test-workflow
          slack-channel: devops-alerts
          failure: false
          AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

  test-report-failure:
    name: Test Slack report failure
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: ./report-deployment-status-to-slack
        with:
          project: Server
          environment: US QA Cloud
          tag: test-workflow-failure
          slack-channel: devops-alerts
          failure: true
          AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

